= [Quantity] * [Price] * (1 - [Discount])

= Table.AddColumn(#"Changed Type", "Income", each [Quantity] * [Price] * (1 - [Discount]), type number)