= Excel.CurrentWorkbook(){[Name="Table1"]}[Content]

= Table.SelectRows(Source, each ([Hidden] = false))

= Table.SelectRows(Source, each ([Hidden] = false) and ([Kind] = "Sheet"))

= Table.SelectColumns(#"Filtered Rows1",{"Name", "Data"})

= Table.RemoveColumns(#"Filtered Rows1",{"Item", "Kind", "Hidden"})

= Table.SelectColumns(#"Invoke Custom Function1",{"Transform File"})

= Table.SelectColumns(#"Invoke Custom Function1",{"Name", "Transform File"})

Sub Refresh_Query()
' Refresh_Query Macro
    Range("B7").Select
    Selection.ListObject.QueryTable.Refresh BackgroundQuery:=False
    ActiveWorkbook.RefreshAll
    ActiveWorkbook.Connections("Query - Managers").Refresh
End Sub

